#!/usr/bin/env python3
"""Plot the Trace-FTQ-L2C hierarchical delta table (docs/exp/2026_07_14_experiment.md,
"Trace-FTQ-L2C 계층별 전체 변화량 표") as a small-multiples grid.

Each column is a trace group, each row is one delta metric from that table
(dIPC, dL1I/L2I MPKI, dFrontend Stall%p, dBackend Inst Stall%p, dL1D/L2D MPKI,
dBackend Data Stall%p, dL2C MPKI). Within a cell, bars are grouped by FTQ size
and colored by L2C partition policy, all measured against the `shared` policy
baseline (delta = policy - shared, same trace/ftq) -- exactly the values in
that table.

Reads directly from the per-(ftq, policy) metrics.csv files under
<run_dir>/summary/fdip_<ftq>/<policy>/metrics.csv (generated by -s beforehand,
or by this run of -s if paired with the table-generating bits).

Usage:
    .venv/bin/python parser/l2c/delta_grid.py outputs/260713_2013_l2c_test \\
        -o outputs/260713_2013_l2c_test/summary/l2c_delta_grid.png
"""
import argparse
import csv
import itertools
from collections import defaultdict
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

BASELINE = "shared"

# Fixed categorical order (dataviz skill palette, light mode). If a run ever
# has more non-baseline L2C policies than colors here, the assignment cycles
# (see `policy_color_map`) instead of crashing -- colors repeat rather than
# staying globally unique past the 6th policy, which is an acceptable
# degradation for a research utility script.
POLICY_COLOR_ORDER = ["#2a78d6", "#1baf7a", "#eda100", "#008300", "#4a3aa7", "#e34948"]


def policy_color_map(policies):
    return dict(zip(policies, itertools.cycle(POLICY_COLOR_ORDER)))

# Matches the doc table's column order exactly. MPKI metrics use "abs" (raw
# policy-minus-shared difference, in MPKI units) rather than a % change --
# with a baseline near 0 (e.g. L2I MPKI at high FTQ) a % change blows up into
# hundreds of percent, which is misleading. dIPC and the stall%p metrics stay
# on a percentage-point-ish scale ("pct"/already-% "abs"), so the overlay
# plot puts them on their own y-axis (see `axis` below) rather than one axis
# shared with the very differently-scaled MPKI values.
METRIC_SPECS = {
    "ipc": {"label": "dIPC (%)", "kind": "pct", "axis": "pct"},
    "l1i_mpki": {"label": "dL1I MPKI", "kind": "abs", "axis": "mpki"},
    "l2i_mpki": {"label": "dL2I MPKI", "kind": "abs", "axis": "mpki"},
    "frontend_instruction_fetch_stall_pct": {"label": "dFrontend Stall%p", "kind": "abs", "axis": "pct"},
    "backend_instruction_stall_pct": {"label": "dBackend Inst Stall%p", "kind": "abs", "axis": "pct"},
    "l1d_mpki": {"label": "dL1D MPKI", "kind": "abs", "axis": "mpki"},
    "l2d_mpki": {"label": "dL2D MPKI", "kind": "abs", "axis": "mpki"},
    "backend_data_stall_pct": {"label": "dBackend Data Stall%p", "kind": "abs", "axis": "pct"},
    "l2c_mpki": {"label": "dL2C MPKI", "kind": "abs", "axis": "mpki"},
    "lli_mpki": {"label": "dLLI MPKI", "kind": "abs", "axis": "mpki"},
    "lld_mpki": {"label": "dLLD MPKI", "kind": "abs", "axis": "mpki"},
}
DEFAULT_METRICS = list(METRIC_SPECS)

# Instruction-side / data-side splits for the overlay plot, both anchored on
# dIPC so each tells a complete "does this side's traffic explain the IPC
# move" story on its own. l2c_mpki (l2i+l2d combined) belongs to neither side
# specifically, so it's left out of both -- use the full DEFAULT_METRICS
# overlay if the combined total is what's needed.
INSTRUCTION_METRICS = ["ipc", "l1i_mpki", "l2i_mpki", "frontend_instruction_fetch_stall_pct", "backend_instruction_stall_pct"]
DATA_METRICS = ["ipc", "l1d_mpki", "l2d_mpki", "backend_data_stall_pct"]

# Per-metric color for the overlay plot, grouped by family so the metric's
# *category* reads at a glance: MPKI metrics share a pastel yellow->orange
# ramp (light->dark, l2c_mpki -- the l2i+l2d total -- gets the darkest/most
# saturated step), kept deliberately soft/desaturated so dIPC's red/blue stay
# the most eye-catching thing on the chart. Stall%p metrics share a green
# ramp. Each ramp is light->dark in the same order the metric appears in
# METRIC_SPECS, so adjacent steps stay distinguishable within a family.
#
# dIPC is sign-colored instead of family-colored, and kept fully saturated
# (not pastel) since it's the headline number -- whether shared vs. this
# policy is an IPC win or loss should read immediately, and it should win
# the eye over the softer MPKI/stall bars. IPC_UP_COLOR (blue) is swapped in
# per-bar when the value is positive; METRIC_STYLE["ipc"]["color"] (red) is
# the base/negative color. The bar-top connecting line stays a neutral ink
# so it doesn't visually merge with either sign's bars.
IPC_UP_COLOR = "#2a78d6"
IPC_LINE_COLOR = "#4a4a46"

METRIC_STYLE = {
    "ipc": {"color": "#e34948"},
    "l1i_mpki": {"color": "#ffe9a8"},
    "l2i_mpki": {"color": "#ffd27f"},
    "frontend_instruction_fetch_stall_pct": {"color": "#a5d6a7"},
    "backend_instruction_stall_pct": {"color": "#4caf50"},
    "l1d_mpki": {"color": "#ffb877"},
    "l2d_mpki": {"color": "#ff9d5c"},
    "backend_data_stall_pct": {"color": "#1b5e20"},
    "l2c_mpki": {"color": "#f2814a"},
}


def discover_ftq_sizes(run_dir):
    summary_dir = run_dir / "summary"
    sizes = []
    for entry in sorted(summary_dir.glob("fdip_*")):
        if entry.is_dir():
            sizes.append(entry.name[len("fdip_") :])
    return sorted(sizes, key=lambda s: int(s))


def discover_policies(run_dir, ftq_sizes):
    policies = set()
    for ftq in ftq_sizes:
        for entry in sorted((run_dir / "summary" / f"fdip_{ftq}").glob("*")):
            if entry.is_dir() and (entry / "metrics.csv").is_file():
                policies.add(entry.name)
    others = sorted(p for p in policies if p != BASELINE)
    return others


def load_metrics(run_dir, ftq, policy, value_keys):
    path = run_dir / "summary" / f"fdip_{ftq}" / policy / "metrics.csv"
    if not path.is_file():
        raise SystemExit(f"metrics.csv not found: {path} (run -s with the table bits first)")

    grouped = defaultdict(list)
    with path.open(newline="", encoding="utf-8") as fp:
        for row in csv.DictReader(fp):
            if row.get("status") == "ok":
                grouped[row["trace_group"]].append(row)

    out = {}
    for group, rows in grouped.items():
        values = {}
        for key in value_keys:
            vals = [float(row[key]) for row in rows if row.get(key) not in (None, "")]
            values[key] = sum(vals) / len(vals) if vals else None
        out[group] = values
    return out


def discover_traces(run_dir, ftq_sizes, policies):
    traces = set()
    for ftq in ftq_sizes:
        for policy in [BASELINE] + policies:
            path = run_dir / "summary" / f"fdip_{ftq}" / policy / "metrics.csv"
            if not path.is_file():
                continue
            with path.open(newline="", encoding="utf-8") as fp:
                for row in csv.DictReader(fp):
                    if row.get("status") == "ok":
                        traces.add(row["trace_group"])
    return sorted(traces)


def collect_raw_values(run_dir, ftq_sizes, policies, metric_keys):
    """Returns raw[(ftq, policy)][trace][key] = value, for policy in [BASELINE]+policies."""
    raw = {}
    for ftq in ftq_sizes:
        for policy in [BASELINE] + policies:
            raw[(ftq, policy)] = load_metrics(run_dir, ftq, policy, metric_keys)
    return raw


def build_deltas(run_dir, ftq_sizes, policies, traces, metric_keys, kind_overrides=None, raw=None):
    """Returns deltas[metric][trace][ftq][policy] = delta vs shared baseline.

    By default each metric's delta "kind" (pct change vs. raw difference)
    comes from METRIC_SPECS; pass `kind_overrides={key: "pct"|"abs"}` to
    compute a different flavor for specific metrics (e.g. MPKI-as-%-change
    for the doc's summary table, vs. MPKI-as-raw-delta for the plots).
    """
    kind_overrides = kind_overrides or {}
    if raw is None:
        raw = collect_raw_values(run_dir, ftq_sizes, policies, metric_keys)

    deltas = {key: {t: {} for t in traces} for key in metric_keys}
    for ftq in ftq_sizes:
        base = raw[(ftq, BASELINE)]
        for trace in traces:
            base_vals = base.get(trace, {})
            for policy in policies:
                pol_vals = raw[(ftq, policy)].get(trace, {})
                for key in metric_keys:
                    b = base_vals.get(key)
                    p = pol_vals.get(key)
                    kind = kind_overrides.get(key, METRIC_SPECS[key]["kind"])
                    if (key == "l2i_mpki" and policy == "0i8d") or (key == "l2d_mpki" and policy == "8i0d"):
                        # 0i8d gives L2C zero instruction ways, and 8i0d gives
                        # L2C zero data ways. The corresponding L2I/L2D metric
                        # is structurally not applicable rather than a cache
                        # improvement over shared. Define the delta as 0 so the
                        # table/plot does not overstate a metric that stopped
                        # applying.
                        d = 0.0
                    elif b is None or p is None:
                        d = None
                    elif kind == "pct":
                        d = (p / b - 1) * 100 if b else None
                    else:
                        d = p - b
                    deltas[key].setdefault(trace, {}).setdefault(ftq, {})[policy] = d
    return deltas


def write_raw_csv(raw, ftq_sizes, policies, traces, metric_keys, output_path):
    """The "원본 수치 표" -- every (trace, ftq, policy) incl. `shared`, raw values."""
    with output_path.open("w", newline="", encoding="utf-8") as fp:
        writer = csv.writer(fp)
        writer.writerow(["trace", "ftq", "policy"] + metric_keys)
        for trace in traces:
            for ftq in ftq_sizes:
                for policy in [BASELINE] + policies:
                    vals = raw[(ftq, policy)].get(trace, {})
                    writer.writerow([trace, ftq, policy] + [vals.get(k, "") for k in metric_keys])


def write_delta_csv(deltas, ftq_sizes, policies, traces, metric_keys, output_path):
    """A delta table (policy vs. `shared`, no baseline rows) -- used for both
    the MPKI-as-%% and MPKI-as-raw-delta variants, just with different `deltas`.
    """
    with output_path.open("w", newline="", encoding="utf-8") as fp:
        writer = csv.writer(fp)
        writer.writerow(["trace", "ftq", "policy"] + [f"d_{k}" for k in metric_keys])
        for trace in traces:
            for ftq in ftq_sizes:
                for policy in policies:
                    row = [deltas[k][trace][ftq].get(policy) for k in metric_keys]
                    writer.writerow([trace, ftq, policy] + ["" if v is None else v for v in row])


def plot_grid(deltas, traces, ftq_sizes, policies, metric_keys, output_path, title):
    n_rows = len(metric_keys)
    n_cols = len(traces)
    policy_colors = policy_color_map(policies)

    fig, axes = plt.subplots(
        n_rows, n_cols, figsize=(2.6 * n_cols, 2.2 * n_rows), sharex=True, squeeze=False
    )

    n_policies = len(policies)
    bar_width = 0.8 / n_policies
    x = list(range(len(ftq_sizes)))

    for row, key in enumerate(metric_keys):
        spec = METRIC_SPECS[key]
        for col, trace in enumerate(traces):
            ax = axes[row][col]
            for i, policy in enumerate(policies):
                offsets = [xi + (i - (n_policies - 1) / 2) * bar_width for xi in x]
                values = [deltas[key][trace][ftq].get(policy) for ftq in ftq_sizes]
                values = [v if v is not None else 0 for v in values]
                ax.bar(
                    offsets,
                    values,
                    width=bar_width,
                    color=policy_colors[policy],
                    label=policy,
                    zorder=3,
                )
            ax.axhline(0, color="#52514e", linewidth=0.8, zorder=2)
            ax.set_xticks(x)
            ax.set_xticklabels([str(f) for f in ftq_sizes], fontsize=8)
            ax.tick_params(axis="y", labelsize=7)
            ax.grid(axis="y", color="#e3e2dd", linewidth=0.6, zorder=0)
            for spine in ("top", "right"):
                ax.spines[spine].set_visible(False)

            if row == 0:
                ax.set_title(trace, fontsize=9)
            if col == 0:
                ax.set_ylabel(spec["label"], fontsize=8)
            if row == n_rows - 1:
                ax.set_xlabel("FTQ", fontsize=8)

    handles = [plt.Rectangle((0, 0), 1, 1, color=policy_colors[p]) for p in policies]
    fig.legend(
        handles,
        policies,
        loc="upper center",
        ncol=min(len(policies), 6),
        frameon=False,
        bbox_to_anchor=(0.5, 1.0 + 0.35 / (2.2 * n_rows)),
        fontsize=9,
    )
    fig.suptitle(title, fontsize=11, y=1.0 + 0.7 / (2.2 * n_rows))
    fig.tight_layout(rect=(0, 0, 1, 1.0))
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


SIDES = [("data", DATA_METRICS), ("instruction", INSTRUCTION_METRICS)]


def plot_overlay(deltas, traces, ftq_sizes, policies, output_path, title):
    """One wide subplot per trace, stacked top-to-bottom (traces get full
    figure width instead of splitting it into columns). Each FTQ block is
    split into two adjacent halves -- all policies under "data" on the left,
    then all policies under "instruction" on the right -- each x-slot showing
    only that side's metrics as grouped bars (raw delta value, no
    normalization); dIPC is repeated in every slot as a shared anchor and its
    bar-top line is drawn separately within each half (broken between data
    and instruction, and between FTQ blocks) so it never implies continuity
    across a side or FTQ change. Bars split across two y-axes by unit: MPKI
    metrics (left) vs. %-scale metrics -- dIPC and the stall%p metrics
    (right) -- via `METRIC_SPECS[key]["axis"]`. Both axes are forced to
    symmetric limits around 0 so their zero-lines coincide visually even
    though their scales differ. `l2c_mpki` (l2i+l2d combined) belongs to
    neither side and is left out. Scales cleanly with however many traces,
    FTQ sizes, or L2C policies are actually present in the run (all
    discovered dynamically -- nothing here assumes a fixed count).
    """
    n_rows = len(traces)
    n_policies = len(policies)
    n_sides = len(SIDES)
    x_keys = [(ftq, policy, side) for ftq in ftq_sizes for side, _ in SIDES for policy in policies]
    x = list(range(len(x_keys)))
    legend_metrics = [k for _, metrics in SIDES for k in metrics if k != "ipc"]
    legend_metrics = ["ipc"] + legend_metrics

    fig_width = max(10.0, 0.55 * len(x_keys) + 2.0)
    fig, axes = plt.subplots(n_rows, 1, figsize=(fig_width, 2.6 * n_rows), squeeze=False)
    axes = axes[:, 0]

    for row, trace in enumerate(traces):
        ax = axes[row]
        ax2 = ax.twinx()
        axis_of = {"mpki": ax, "pct": ax2}
        max_abs = {"mpki": 0.0, "pct": 0.0}
        ipc_points = []

        for xi, (ftq, policy, side) in enumerate(x_keys):
            side_metrics = dict(SIDES)[side]
            n_side_metrics = len(side_metrics)
            bar_width = 0.8 / n_side_metrics
            for m, key in enumerate(side_metrics):
                val = deltas[key][trace][ftq].get(policy)
                offset = xi + (m - (n_side_metrics - 1) / 2) * bar_width
                style = METRIC_STYLE[key]
                axis_key = METRIC_SPECS[key]["axis"]
                bar_color = IPC_UP_COLOR if (key == "ipc" and val is not None and val > 0) else style["color"]
                axis_of[axis_key].bar(
                    [offset],
                    [val if val is not None else 0],
                    width=bar_width,
                    color=bar_color,
                    zorder=3,
                )
                if val is not None:
                    max_abs[axis_key] = max(max_abs[axis_key], abs(val))
                if key == "ipc":
                    if val is not None:
                        ipc_points.append((offset, val))
                    else:
                        ipc_points.append(None)

        # dIPC is the headline metric -- connect its bar tops within each
        # data/instruction half separately (broken at every side boundary,
        # which includes every FTQ boundary) so the line never implies
        # continuity across a side change or an FTQ change.
        for group_start in range(0, len(x_keys), n_policies):
            seg = ipc_points[group_start : group_start + n_policies]
            pts = [p for p in seg if p is not None]
            if len(pts) >= 2:
                axis_of["pct"].plot(
                    [p[0] for p in pts],
                    [p[1] for p in pts],
                    color=IPC_LINE_COLOR,
                    linewidth=1.3,
                    marker="o",
                    markersize=3.5,
                    zorder=4,
                )

        # Symmetric limits around 0 on each axis independently, so the two
        # differently-scaled axes still show a common, aligned zero-line.
        pad = 1.15
        mpki_limit = (max_abs["mpki"] * pad) or 1.0
        pct_limit = (max_abs["pct"] * pad) or 1.0
        # Inverted on purpose: "up" means improvement on both axes now (fewer
        # misses is as much a win as higher IPC), instead of up meaning
        # opposite things on the two axes.
        ax.set_ylim(mpki_limit, -mpki_limit)
        ax2.set_ylim(-pct_limit, pct_limit)

        ax.axhline(0, color="#52514e", linewidth=0.8, zorder=2)
        for boundary in range(n_policies * n_sides, len(x_keys), n_policies * n_sides):
            ax.axvline(boundary - 0.5, color="#8a8980", linewidth=0.8, zorder=1)
        for boundary in range(n_policies, len(x_keys), n_policies):
            if boundary % (n_policies * n_sides) != 0:
                ax.axvline(boundary - 0.5, color="#e3e2dd", linewidth=0.6, linestyle=":", zorder=1)
        ax.set_xticks(x)
        ax.set_xticklabels([f"{ftq}\n{policy}\n{side}" for ftq, policy, side in x_keys], fontsize=6.5)
        ax.tick_params(axis="y", labelsize=8)
        ax2.tick_params(axis="y", labelsize=8)
        ax.grid(axis="y", color="#e3e2dd", linewidth=0.6, zorder=0)
        ax.spines["top"].set_visible(False)
        ax2.spines["top"].set_visible(False)
        ax.set_ylabel(f"{trace}\nMPKI (↑ = better)", fontsize=9)
        ax2.set_ylabel("%", fontsize=9)

    axes[-1].set_xlabel("FTQ / side (data | instruction) / L2C policy", fontsize=9)

    # Three separate legends -- IPC / data / instruction -- instead of one
    # flat wrapped row, so which color belongs to which category is visible
    # at a glance rather than left to the reader to infer from row-wrapping.
    legend_y = 1.0 + 0.6 / (2.6 * n_rows)
    groups = [
        (
            "IPC",
            [METRIC_STYLE["ipc"]["color"], IPC_UP_COLOR],
            ["dIPC (%) ≤ 0", "dIPC (%) > 0"],
            0.14,
        ),
        (
            "Data",
            [METRIC_STYLE[k]["color"] for k in DATA_METRICS if k != "ipc"],
            [METRIC_SPECS[k]["label"] for k in DATA_METRICS if k != "ipc"],
            0.46,
        ),
        (
            "Instruction",
            [METRIC_STYLE[k]["color"] for k in INSTRUCTION_METRICS if k != "ipc"],
            [METRIC_SPECS[k]["label"] for k in INSTRUCTION_METRICS if k != "ipc"],
            0.80,
        ),
    ]
    for group_title, colors, labels, x in groups:
        handles = [plt.Rectangle((0, 0), 1, 1, color=c) for c in colors]
        legend = fig.legend(
            handles,
            labels,
            title=group_title,
            loc="upper center",
            ncol=1,
            frameon=False,
            bbox_to_anchor=(x, legend_y),
            fontsize=8,
            title_fontsize=8.5,
        )
        legend.get_title().set_fontweight("bold")
    fig.suptitle(title, fontsize=11, y=1.0 + 1.0 / (2.6 * n_rows))
    fig.tight_layout(rect=(0, 0, 1, 1.0))
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


# v2 of the overlay: same source data (`deltas`, from the same metrics.csv /
# CSV outputs as the v1 plot -- nothing is re-fetched), but the 3 stall%p
# metrics are dropped and data-side/instruction-side MPKI (now including the
# LLC-level, origin-split lli_mpki/lld_mpki) are drawn together in one group
# per (ftq, policy) slot instead of split into separate data/instruction
# halves. Useful as a denser, stall-free read of just "does this policy
# trade instruction-side MPKI for data-side MPKI (or vice versa) at each
# cache level, and what happens to IPC."
MERGED_METRICS = ["ipc", "l1d_mpki", "l2d_mpki", "lld_mpki", "l1i_mpki", "l2i_mpki", "lli_mpki"]

# v2 uses its own family colors instead of METRIC_STYLE's pastel-orange-for-
# all-MPKI scheme, because v1 keeps data/instruction apart by position (left
# half vs. right half) so color doesn't need to carry that distinction --
# but v2 merges them into one group, so color is the only thing separating
# "this bar is data-side" from "this bar is instruction-side". Data gets a
# yellow ramp, instruction a green ramp, each light->dark L1->L2->LLC.
MERGED_METRIC_STYLE = {
    "l1d_mpki": {"color": "#fff0a8"},
    "l2d_mpki": {"color": "#ffd24d"},
    "lld_mpki": {"color": "#e0a300"},
    "l1i_mpki": {"color": "#c9e8b0"},
    "l2i_mpki": {"color": "#85c96a"},
    "lli_mpki": {"color": "#3f8f3f"},
}


# Workload classification from docs/exp/2026_07_15_analysis.md, "FTQ=0
# Workload 분류": at ftq=0, which side's metric IPC tracks when the L2C
# policy changes. Instruction/frontend-follow trades data MPKI for less
# frontend stall; Data-follow does the opposite; Mixed/balanced isn't
# explained by either side alone. Specific to the l2c_test 8-group set --
# `group_traces()` falls back gracefully (an "Other" bucket) if a run's
# traces don't match, so it's safe to pass for any run.
WORKLOAD_GROUPS = [
    ("Instruction/frontend-follow", ["delta", "sierra.a.6", "tango"]),
    ("Data-follow", ["merced", "yankee"]),
    ("Mixed/balanced", ["bravo", "sierra.a.4", "tahoe"]),
]


def group_traces(traces, groups=WORKLOAD_GROUPS):
    """Reorder `traces` by `groups` (list of (name, [trace,...])), keeping
    each group's internal order as listed. Traces present but not in any
    group are appended at the end under "Other". Returns (ordered_traces,
    group_labels) where group_labels is [(row_index, group_name), ...] for
    the row each group starts at in the ordered list.
    """
    trace_set = set(traces)
    ordered = []
    labels = []
    for name, members in groups:
        present = [t for t in members if t in trace_set]
        if not present:
            continue
        labels.append((len(ordered), name))
        ordered.extend(present)
    leftover = [t for t in traces if t not in set(ordered)]
    if leftover:
        labels.append((len(ordered), "Other"))
        ordered.extend(leftover)
    return ordered, labels


def plot_overlay_merged(deltas, traces, ftq_sizes, policies, output_path, title, group_labels=None):
    """One wide subplot per trace. Each (FTQ, policy) gets a single group of
    bars -- dIPC (sign-colored red/blue), data-side MPKI (L1D/L2D/LLD,
    yellow ramp) and instruction-side MPKI (L1I/L2I/LLI, green ramp) -- with
    no data|instruction split and no stall%p metrics. dIPC bar-tops are
    connected within each FTQ block (broken at FTQ boundaries only). Same
    dual-axis (MPKI left, % right, symmetric around 0) treatment as the v1
    overlay. Scales the same way v1 does: traces, FTQ sizes, and L2C
    policies are all whatever the caller passes in.

    `group_labels`, if given (see `group_traces()`), is [(row_index,
    group_name), ...] -- the row each group starts at. `traces` must already
    be in that grouped order (group_traces returns both together). Each
    group's first row gets a bold left-aligned title so the vertical
    stacking reads as labeled clusters instead of one flat trace list.
    """
    group_labels = dict(group_labels or [])
    n_rows = len(traces)
    n_policies = len(policies)
    x_keys = [(ftq, policy) for ftq in ftq_sizes for policy in policies]
    x = list(range(len(x_keys)))
    n_metrics = len(MERGED_METRICS)
    bar_width = 0.8 / n_metrics

    fig_width = max(10.0, 0.45 * len(x_keys) + 2.0)
    fig, axes = plt.subplots(n_rows, 1, figsize=(fig_width, 2.6 * n_rows), squeeze=False)
    axes = axes[:, 0]

    for row, trace in enumerate(traces):
        ax = axes[row]
        ax2 = ax.twinx()
        axis_of = {"mpki": ax, "pct": ax2}
        max_abs = {"mpki": 0.0, "pct": 0.0}
        ipc_points = []
        l2i_points = []
        l2d_points = []

        for xi, (ftq, policy) in enumerate(x_keys):
            for m, key in enumerate(MERGED_METRICS):
                val = deltas[key][trace][ftq].get(policy)
                offset = xi + (m - (n_metrics - 1) / 2) * bar_width
                base_color = METRIC_STYLE["ipc"]["color"] if key == "ipc" else MERGED_METRIC_STYLE[key]["color"]
                axis_key = METRIC_SPECS[key]["axis"]
                bar_color = IPC_UP_COLOR if (key == "ipc" and val is not None and val > 0) else base_color
                axis_of[axis_key].bar(
                    [offset],
                    [val if val is not None else 0],
                    width=bar_width,
                    color=bar_color,
                    zorder=3,
                )
                if val is not None:
                    max_abs[axis_key] = max(max_abs[axis_key], abs(val))
                if key == "ipc":
                    ipc_points.append((offset, val) if val is not None else None)
                elif key == "l2i_mpki":
                    # 0i8d's d_l2i_mpki is forced to 0 (structural, not a
                    # real trend point -- see build_deltas), so it's skipped
                    # here rather than pulling the trend line down to 0.
                    l2i_points.append((offset, val) if (val is not None and policy != "0i8d") else None)
                elif key == "l2d_mpki":
                    # Same treatment for 8i0d's structurally absent d_l2d_mpki.
                    l2d_points.append((offset, val) if (val is not None and policy != "8i0d") else None)

        # Trend lines broken at every FTQ boundary (one group per FTQ
        # block), same treatment as the dIPC line: dL2I in green (matching
        # the instruction-side bar family), dL2D in yellow (matching the
        # data-side bar family), so each line reads as "the trend of its
        # own bar color."
        line_series = [
            (ipc_points, axis_of["pct"], IPC_LINE_COLOR),
            (l2i_points, axis_of["mpki"], MERGED_METRIC_STYLE["l2i_mpki"]["color"]),
            (l2d_points, axis_of["mpki"], MERGED_METRIC_STYLE["l2d_mpki"]["color"]),
        ]
        for points, line_axis, color in line_series:
            for group_start in range(0, len(x_keys), n_policies):
                seg = points[group_start : group_start + n_policies]
                pts = [p for p in seg if p is not None]
                if len(pts) >= 2:
                    line_axis.plot(
                        [p[0] for p in pts],
                        [p[1] for p in pts],
                        color=color,
                        linewidth=1.3,
                        marker="o",
                        markersize=3.5,
                        zorder=4,
                    )

        pad = 1.15
        mpki_limit = (max_abs["mpki"] * pad) or 1.0
        pct_limit = (max_abs["pct"] * pad) or 1.0
        # Inverted on purpose: "up" means improvement on both axes now (fewer
        # misses is as much a win as higher IPC), instead of up meaning
        # opposite things on the two axes.
        ax.set_ylim(mpki_limit, -mpki_limit)
        ax2.set_ylim(-pct_limit, pct_limit)

        ax.axhline(0, color="#52514e", linewidth=0.8, zorder=2)
        for boundary in range(n_policies, len(x_keys), n_policies):
            ax.axvline(boundary - 0.5, color="#8a8980", linewidth=0.8, zorder=1)
        ax.set_xticks(x)
        ax.set_xticklabels([f"{ftq}\n{policy}" for ftq, policy in x_keys], fontsize=6.5)
        ax.tick_params(axis="y", labelsize=8)
        ax2.tick_params(axis="y", labelsize=8)
        ax.grid(axis="y", color="#e3e2dd", linewidth=0.6, zorder=0)
        ax.spines["top"].set_visible(False)
        ax2.spines["top"].set_visible(False)
        ax.set_ylabel(f"{trace}\nMPKI (↑ = better)", fontsize=9)
        ax2.set_ylabel("%", fontsize=9)

        if row in group_labels:
            # A heavier top spine plus a left-aligned bold title mark where
            # each workload-classification group starts, so the stacked
            # traces read as labeled clusters rather than one flat list.
            if row != 0:
                ax.spines["top"].set_visible(True)
                ax.spines["top"].set_linewidth(1.4)
                ax.spines["top"].set_color("#3a3a36")
            ax.set_title(group_labels[row], loc="left", fontsize=12, fontweight="bold", color="#3a3a36", pad=8)

    axes[-1].set_xlabel("FTQ / L2C policy", fontsize=9)

    legend_y = 1.0 + 0.6 / (2.6 * n_rows)
    groups = [
        (
            "IPC",
            [METRIC_STYLE["ipc"]["color"], IPC_UP_COLOR],
            ["dIPC (%) ≤ 0", "dIPC (%) > 0"],
            0.22,
        ),
        (
            "Data",
            [MERGED_METRIC_STYLE[k]["color"] for k in ("l1d_mpki", "l2d_mpki", "lld_mpki")],
            [METRIC_SPECS[k]["label"] for k in ("l1d_mpki", "l2d_mpki", "lld_mpki")],
            0.5,
        ),
        (
            "Instruction",
            [MERGED_METRIC_STYLE[k]["color"] for k in ("l1i_mpki", "l2i_mpki", "lli_mpki")],
            [METRIC_SPECS[k]["label"] for k in ("l1i_mpki", "l2i_mpki", "lli_mpki")],
            0.78,
        ),
    ]
    for group_title, colors, labels, x_anchor in groups:
        handles = [plt.Rectangle((0, 0), 1, 1, color=c) for c in colors]
        legend = fig.legend(
            handles,
            labels,
            title=group_title,
            loc="upper center",
            ncol=1,
            frameon=False,
            bbox_to_anchor=(x_anchor, legend_y),
            fontsize=8,
            title_fontsize=8.5,
        )
        legend.get_title().set_fontweight("bold")
    fig.suptitle(title, fontsize=11, y=1.0 + 1.0 / (2.6 * n_rows))
    fig.tight_layout(rect=(0, 0, 1, 1.0))
    fig.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("run_dir", help="Run output directory, e.g. outputs/260713_2013_l2c_test")
    parser.add_argument(
        "--traces",
        nargs="+",
        default=None,
        help="Trace groups to include, left-to-right. Default: all groups found under the run.",
    )
    parser.add_argument(
        "--ftq",
        nargs="+",
        default=None,
        help="FTQ sizes to include. Default: all fdip_<n> dirs found under <run_dir>/summary.",
    )
    parser.add_argument(
        "--policies",
        nargs="+",
        default=None,
        help="Non-baseline L2C policies to include. Default: all found besides 'shared'.",
    )
    parser.add_argument(
        "--metrics",
        nargs="+",
        default=None,
        choices=sorted(METRIC_SPECS),
        help="Delta metrics to plot, top-to-bottom. Default: the full doc-table column set.",
    )
    parser.add_argument("-o", "--output", required=True, help="Output PNG path for the grid plot.")
    parser.add_argument(
        "--overlay-output",
        default=None,
        help="If set, also write a per-trace overlay plot (data-side and instruction-side metrics side by "
        "side per ftq/policy, dual MPKI/%% axes) to this path.",
    )
    parser.add_argument(
        "--overlay-merged-output",
        default=None,
        help="If set, also write a v2 overlay plot: same data as --overlay-output but with the 3 stall%% "
        "metrics dropped and data-side/instruction-side MPKI merged into one group per ftq/policy.",
    )
    args = parser.parse_args()

    run_dir = Path(args.run_dir)
    if not run_dir.is_dir():
        raise SystemExit(f"Run directory not found: {run_dir}")

    ftq_sizes = args.ftq or discover_ftq_sizes(run_dir)
    if not ftq_sizes:
        raise SystemExit(f"No fdip_<n> summary directories found under {run_dir}/summary")

    policies = args.policies or discover_policies(run_dir, ftq_sizes)
    if not policies:
        raise SystemExit(f"No non-'{BASELINE}' L2C policy summary directories found under {run_dir}/summary")

    traces = args.traces or discover_traces(run_dir, ftq_sizes, policies)
    if not traces:
        raise SystemExit(f"No trace groups found under {run_dir}/summary")

    metric_keys = args.metrics or DEFAULT_METRICS

    raw = collect_raw_values(run_dir, ftq_sizes, policies, metric_keys)
    deltas = build_deltas(run_dir, ftq_sizes, policies, traces, metric_keys, raw=raw)

    # The three CSVs from the doc's analysis process, saved alongside the
    # plots: raw values (incl. shared), delta with MPKI-as-%-change (matches
    # the doc's "MPKI % 반영" table), and delta with MPKI-as-raw-value (matches
    # the doc's highlighted raw-delta table and what the plots above draw).
    summary_dir = Path(args.output).parent
    summary_dir.mkdir(parents=True, exist_ok=True)
    mpki_keys = [k for k in metric_keys if METRIC_SPECS[k]["axis"] == "mpki"]

    raw_csv_path = summary_dir / "l2c_raw_values.csv"
    write_raw_csv(raw, ftq_sizes, policies, traces, metric_keys, raw_csv_path)
    print(f"Saved {raw_csv_path}")

    delta_pct_csv_path = summary_dir / "l2c_delta_pct.csv"
    deltas_pct = build_deltas(
        run_dir, ftq_sizes, policies, traces, metric_keys, kind_overrides={k: "pct" for k in mpki_keys}, raw=raw
    )
    write_delta_csv(deltas_pct, ftq_sizes, policies, traces, metric_keys, delta_pct_csv_path)
    print(f"Saved {delta_pct_csv_path}")

    delta_raw_csv_path = summary_dir / "l2c_delta_raw.csv"
    deltas_raw = build_deltas(
        run_dir, ftq_sizes, policies, traces, metric_keys, kind_overrides={k: "abs" for k in mpki_keys}, raw=raw
    )
    write_delta_csv(deltas_raw, ftq_sizes, policies, traces, metric_keys, delta_raw_csv_path)
    print(f"Saved {delta_raw_csv_path}")

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plot_grid(
        deltas,
        traces,
        ftq_sizes,
        policies,
        metric_keys,
        output_path,
        title=f"{run_dir.name}: L2C partition delta vs {BASELINE} (by trace x FTQ)",
    )
    print(f"Saved {output_path}")

    if args.overlay_output:
        overlay_path = Path(args.overlay_output)
        overlay_path.parent.mkdir(parents=True, exist_ok=True)
        plot_overlay(
            deltas,
            traces,
            ftq_sizes,
            policies,
            overlay_path,
            title=f"{run_dir.name}: L2C partition delta vs {BASELINE} per trace (data | instruction side by side)",
        )
        print(f"Saved {overlay_path}")

    if args.overlay_merged_output:
        overlay_merged_path = Path(args.overlay_merged_output)
        overlay_merged_path.parent.mkdir(parents=True, exist_ok=True)
        grouped_traces, group_labels = group_traces(traces)
        plot_overlay_merged(
            deltas,
            grouped_traces,
            ftq_sizes,
            policies,
            overlay_merged_path,
            title=f"{run_dir.name}: L2C partition delta vs {BASELINE} per trace (data + instruction merged, no stall%%)",
            group_labels=group_labels,
        )
        print(f"Saved {overlay_merged_path}")


if __name__ == "__main__":
    main()
