import os
import re
import glob
import argparse
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Configuration from fdip_cover.py
LABELS = [
    'L1I Hit (FDIP Covered)',
    'L1I Hit (Non-Prefetch)',
    'L1I Merge (Non-Prefetch)',
    'L1I Late Prefetch (Merge)',
    'L1I Miss'
]

SHORT_LABELS = [
    'Hit (FDIP)',
    'Hit (Base)',
    'Merge (Base)',
    'Merge (FDIP)',
    'Miss'
]

COLORS = ['#2ca02c', '#1f77b4', '#aec7e8', '#98df8a', '#d62728']

def parse_file(filepath):
    """
    Parses a single text file to extract category percentages.
    """
    data = {}
    try:
        with open(filepath, 'r') as f:
            lines = f.readlines()
            
        start_parsing = False
        for line in lines:
            if "Category" in line and "Percent" in line:
                start_parsing = True
                continue
            if start_parsing:
                if "TOTAL" in line or "-------" in line:
                    continue
                if not line.strip():
                    continue
                
                parts = line.split('|')
                if len(parts) >= 3:
                    category = parts[0].strip()
                    try:
                        percent_str = parts[2].strip().replace('%', '')
                        percent = float(percent_str)
                        data[category] = percent
                    except ValueError:
                        pass
            
            # Check for Average IPC (outside or inside table parsing logic, usually at end)
            if "Average IPC:" in line:
                parts = line.split(':')
                if len(parts) >= 2:
                    try:
                        data['IPC'] = float(parts[1].strip())
                    except ValueError:
                        pass
                        
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
        return None
    return data

def get_data_for_prefix(prefix):
    """
    Finds files matching {prefix}_fdip_*.txt in the same directory as this script.
    Returns a DataFrame indexed by FTQ Size (int).
    """
    script_dir = os.path.dirname(os.path.abspath(__file__))
    files = glob.glob(os.path.join(script_dir, f"{prefix}_fdip_*.txt"))
    results = {}

    # Always include no_fdip.txt as baseline (Size 0)
    no_fdip_path = os.path.join(script_dir, "no_fdip.txt")
    if os.path.exists(no_fdip_path):
        data = parse_file(no_fdip_path)
        if data:
            row = {label: data.get(label, 0.0) for label in LABELS}
            if 'IPC' in data:
                row['IPC'] = data['IPC']
            results[0] = row # 0 represents No FDIP

    for f in files:
        # Extract size from filename: s_fdip_64.txt -> 64
        match = re.search(r'fdip_(\d+)\.txt$', f)
        if match:
            size = int(match.group(1))
            data = parse_file(f)
            if data:
                # Ensure all logical keys exist, default to 0
                row = {label: data.get(label, 0.0) for label in LABELS}
                if 'IPC' in data:
                    row['IPC'] = data['IPC']
                results[size] = row
                
    df = pd.DataFrame(results).T # Transpose: Index=Size, Cols=Categories
    if not df.empty:
        df = df.sort_index()
    return df

def get_data_from_summary(summary_dir):
    """
    Reads summary/fdip_*/fdip_*.txt reports generated by fdip_cover.py.
    Returns a DataFrame indexed by FTQ Size (int).
    """
    files = glob.glob(os.path.join(summary_dir, "fdip_*", "fdip_*.txt"))
    results = {}

    for f in files:
        parent = os.path.basename(os.path.dirname(f))
        match = re.match(r'fdip_(\d+)$', parent)
        if not match:
            continue

        size = int(match.group(1))
        data = parse_file(f)
        if data:
            row = {label: data.get(label, 0.0) for label in LABELS}
            if 'IPC' in data:
                row['IPC'] = data['IPC']
            results[size] = row

    df = pd.DataFrame(results).T
    if not df.empty:
        df = df.sort_index()
    return df

def plot_config(df, config_name, output_filename):
    if df.empty:
        print(f"No data found for configuration: {config_name}")
        return

    # Ensure columns follow the specific bottom-to-top order
    # Labels in code order: 0:Hit(FDIP), 1:Hit(Base), 2:Merge(Base), 3:Merge(FDIP), 4:Miss
    # plot(stacked=True) stacks columns from left to right on top of each other.
    # So we want df columns to be in the order we want stacked (Bottom -> Top).
    
    # So we want df columns to be in the order we want stacked (Bottom -> Top).
    
    df_bars = df[LABELS] # enforce order for bars
    
    fig, ax = plt.subplots(figsize=(12, 7))
    
    # Plot
    # We use color mapping
    df_bars.plot(kind='bar', stacked=True, ax=ax, color=COLORS, width=0.6, edgecolor='black', linewidth=0.5)
    
    ax.set_title(f'L1I Demand Access Breakdown - {config_name}', fontsize=14, fontweight='bold')
    ax.set_xlabel('FTQ Size', fontsize=12)
    ax.set_ylabel('Percentage (%)', fontsize=12)
    ax.set_ylim(0, 100)
    
    # Grid
    ax.grid(axis='y', linestyle='--', alpha=0.5)
    ax.set_axisbelow(True)
    
    # Legend handled lower down to combine with IPC
    
    # Rotate X labels
    plt.xticks(rotation=0)
    
    # Custom X-axis labels: Replace 0 with "No FDIP" using df.index
    new_labels = ["No FDIP" if idx == 0 else str(idx) for idx in df.index]
    ax.set_xticklabels(new_labels)
    
    # Plot IPC on secondary Axis if available
    if 'IPC' in df.columns:
        ax2 = ax.twinx()
        # Plot IPC. Make sure x-axis aligns. 
        # Standard plot uses 0..N for x values when labels are strings?
        # Pandas bar plot uses integer indices 0..N-1 for bars if index is not numeric?
        # But df index is numeric (0, 2, 4...).
        # Pandas plot puts bars at 0, 1, 2... and sets ticks.
        # So we should plot the line at 0, 1, 2... corresponding to the rows.
        x_indices = np.arange(len(df))
        ax2.plot(x_indices, df['IPC'], color='black', marker='o', linewidth=2, linestyle='-', label='Average IPC')
        
        # Add values above points
        for x, y in zip(x_indices, df['IPC']):
            ax2.text(x, y, f'{y:.4f}', ha='center', va='bottom', fontsize=9, color='black', fontweight='bold')
            
        ax2.set_ylabel('IPC', fontsize=12, color='black')
        ax2.tick_params(axis='y', labelcolor='black')
        
        # Adjust Y-limit for IPC to look nice (e.g., start at 0, slightly above max)
        max_ipc = df['IPC'].max()
        if max_ipc > 0:
            ax2.set_ylim(0, max_ipc * 1.2)
            
        # Combine legends
        handles1, labels1 = ax.get_legend_handles_labels()
        handles2, labels2 = ax2.get_legend_handles_labels()
        
        # Map labels
        short_labels_map = dict(zip(LABELS, SHORT_LABELS))
        new_labels1 = [short_labels_map.get(l, l) for l in labels1]
        
        # Reversed for Stacked Bar, Normal for Line
        final_handles = reversed(handles1)
        final_labels = reversed(new_labels1)
        
        # Add IPC to legend
        all_handles = list(final_handles) + handles2
        all_labels = list(final_labels) + labels2
        
        ax.legend(all_handles, all_labels, title='Category', bbox_to_anchor=(1.08, 1), loc='upper left')
    else:
        # Legend (reversed to match stack order visually)
        handles, labels = ax.get_legend_handles_labels()
        # Map long labels to short labels
        short_labels_map = dict(zip(LABELS, SHORT_LABELS))
        new_labels = [short_labels_map.get(l, l) for l in labels]
        ax.legend(reversed(handles), reversed(new_labels), title='Category', bbox_to_anchor=(1.02, 1), loc='upper left')
    
    # Add value annotations for significant segments
    for c in ax.containers:
        # c is a BarContainer
        # We can iterate bars
        labels_arr = []
        for v in c:
            height = v.get_height()
            if height >= 2.0: # Threshold to show text
                labels_arr.append(f'{height:.1f}')
            else:
                labels_arr.append('')
        ax.bar_label(c, labels=labels_arr, label_type='center', fontsize=8, color='white', fontweight='bold')

    plt.tight_layout()
    plt.savefig(output_filename, dpi=300)
    print(f"Graph saved to {os.path.abspath(output_filename)}")
    plt.close()

def main():
    parser = argparse.ArgumentParser(description='Generate combined FDIP cover graph.')
    parser.add_argument('--summary-dir', help='Run summary directory containing fdip_*/fdip_*.txt reports')
    parser.add_argument('--output', help='Output PNG path for --summary-dir mode')
    args = parser.parse_args()

    if args.summary_dir:
        summary_dir = os.path.abspath(args.summary_dir)
        output = args.output if args.output else os.path.join(summary_dir, 'fdip_breakdown_combined.png')
        df = get_data_from_summary(summary_dir)
        plot_config(df, 'FDIP Cover', output)
        return

    # Configurations
    configs = [
        ('pf', 'Perfect Path FDIP'),
        ('s', 'Stop/Reverted FDIP'),
        ('wp', 'Wrong Path FDIP') # Future proofing
    ]
    
    for prefix, name in configs:
        df = get_data_for_prefix(prefix)
        plot_config(df, name, f'{prefix}_fdip_breakdown_combined.png')

if __name__ == "__main__":
    main()
